- name: Reset rescue user password
  connection: local
  gather_facts: false
  hosts: localhost
  vars:
    org_name: default
    name_prefix: AnsibleDemo
    tags: &tags
      - Key: Customer
        Value: CustomerA
      - Key: Automation
        Value: Ansible
    user: rescue
  tasks:
    - set_fact:
        new_password: "C1sco123!!"
    - name: "Get user account"
      cisco.intersight.intersight_rest_api:
        resource_path: /iam/Users
        validate_certs: false
        query_params:
          $filter: "UserIdOrEmail eq '{{ user }}'"
      register: user_resp
    - name: "Set user password"
      cisco.intersight.intersight_rest_api:
        resource_path: "/iam/LocalUserPasswords/{{ user_resp.api_response.LocalUserPassword.Moid }}"
        validate_certs: false
        api_body: { "InitialPassword": "{{ new_password }}" }
