- name: LAN Connectivity Policy
  cisco.intersight.intersight_rest_api:
    resource_path: /vnic/LanConnectivityPolicies
    query_params:
      $filter: "Name eq '{{ name_prefix }}-lanconnectivity-pol'"
    api_body:
      {
        "Organization":
          {
            "ObjectType": "organization.Organization",
            "Moid": "{{ org_resp.api_response.Moid }}",
          },
        "Name": "{{ name_prefix }}-lanconnectivity-pol",
        "AzureQosEnabled": false,
        "IqnAllocationType": "None",
        "IqnPool": null,
        "PlacementMode": "custom",
        "StaticIqnName": "",
        "TargetPlatform": "FIAttached",
      }
  register: lan_connectivity_policy_res
- debug:
    msg: "lan_connectivity_policy_res: {{ lan_connectivity_policy_res }}"
- set_fact:
    lan_connectivity_policy_moid: "{{ lan_connectivity_policy_res.api_response.Moid }}"

# Get the Ethernet Network Group Policy
- name: "Get Ethernet Network Group Policy Moid"
  cisco.intersight.intersight_rest_api:
    resource_path: /fabric/EthNetworkGroupPolicies
    query_params:
      $filter: "Name eq 'cg-impi-ethnetgrp'"
  register: eth_net_group_resp
# Get the Ethernet Network Control Policy
- name: "Get Ethernet Network Control Policy Moid"
  cisco.intersight.intersight_rest_api:
    resource_path: /fabric/EthNetworkControlPolicies
    query_params:
      $filter: "Name eq 'cg-impi-ethnetctrl'"
  register: eth_net_control_resp
# Get the Ethernet QoS Policy
- name: "Get Ethernet QoS Policy Moid"
  cisco.intersight.intersight_rest_api:
    resource_path: /vnic/EthQosPolicies
    query_params:
      $filter: "Name eq 'MEL-ETH-QOS'"
  register: eth_qos_resp
# Get the Ethernet Network Group Policy
- name: "Get Ethernet Adapter Policy Moid"
  cisco.intersight.intersight_rest_api:
    resource_path: /vnic/EthAdapterPolicies
    query_params:
      $filter: "Name eq 'MEL-VNIC'"
  register: eth_adapter_resp
# Get MAC Address Pool
- name: "Get MAC Address Pool Moid"
  cisco.intersight.intersight_rest_api:
    resource_path: /macpool/Pools
    query_params:
      $filter: "Name eq 'MEL-MAC'"
  register: mac_resp

- name: vNic Ethernet Interface
  cisco.intersight.intersight_rest_api:
    resource_path: /vnic/EthIfs
    query_params:
      $filter: "Name eq 'vnic0' and LanConnectivityPolicy.Moid eq '{{ lan_connectivity_policy_moid }}'"
    api_body:
      {
        "Name": "vnic0",

        "Cdn":
          {
            "ClassId": "vnic.Cdn",
            "ObjectType": "vnic.Cdn",
            "Source": "vnic",
            "Value": "vnic0",
          },
        "EthAdapterPolicy":
          {
            "Moid": "{{ eth_adapter_resp.api_response.Moid }}",
            "ObjectType": "vnic.EthAdapterPolicy",
          },
        "EthNetworkPolicy": null,
        "EthQosPolicy":
          {
            "Moid": "{{ eth_qos_resp.api_response.Moid }}",
            "ObjectType": "vnic.EthQosPolicy",
          },
        "FabricEthNetworkControlPolicy":
          {
            "Moid": "{{ eth_net_control_resp.api_response.Moid }}",
            "ObjectType": "fabric.EthNetworkControlPolicy",
          },
        "FabricEthNetworkGroupPolicy":
          [
            {
              "Moid": "{{ eth_net_group_resp.api_response.Moid }}",
              "ObjectType": "fabric.EthNetworkGroupPolicy",
            },
          ],
        "FailoverEnabled": true,
        "LanConnectivityPolicy":
          {
            "Moid": "{{ lan_connectivity_policy_moid }}",
            "ObjectType": "vnic.LanConnectivityPolicy",
          },
        "MacAddressType": "POOL",
        "MacPool":
          {
            "Moid": "{{ mac_resp.api_response.Moid }}",
            "ObjectType": "macpool.Pool",
          },

        "Order": 0,
        "PinGroupName": "",
        "Placement":
          {
            "AutoPciLink": true,
            "AutoSlotId": true,
            "ClassId": "vnic.PlacementSettings",
            "Id": "",
            "ObjectType": "vnic.PlacementSettings",
            "PciLink": 0,
            "PciLinkAssignmentMode": "Custom",
            "SwitchId": "A",
            "Uplink": 0,
          },
        "StandbyVifId": 0,
        "VifId": 0,
      }
